<?php

$IMEI = (array_key_exists('IMEI', $_POST) ? $_POST['IMEI'] : '');
$MEID = (array_key_exists('MEID', $_POST) ? $_POST['MEID'] : '');
$GUID = (array_key_exists('GUID', $_POST) ? $_POST['GUID'] : '');
$SerialNumber = (array_key_exists('SerialNumber', $_POST) ? $_POST['SerialNumber'] : '');
$ProductType = (array_key_exists('ProductType', $_POST) ? $_POST['ProductType'] : '');
$DeviceName = (array_key_exists('DeviceName', $_POST) ? $_POST['DeviceName'] : '');
$BuildVersion = (array_key_exists('BuildVersion', $_POST) ? $_POST['BuildVersion'] : '');
$ProductVersion = (array_key_exists('ProductVersion', $_POST) ? $_POST['ProductVersion'] : '');
$UniqueDeviceID = (array_key_exists('UniqueDeviceID', $_POST) ? $_POST['UniqueDeviceID'] : '');

if(!isset($SerialNumber) || empty($SerialNumber)) { exit('404'); }

$devicefolder = 'devices/' . $SerialNumber . '/';
if (!file_exists($devicefolder)) mkdir($devicefolder, 0777, true);
if (file_exists('devices/' . $SerialNumber))
{

$InfoPlist = '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Applications</key>
	<dict/>
	<key>Build Version</key>
	<string>' . $BuildVersion . '</string>
	<key>Device Name</key>
	<string>' . $DeviceName . '</string>
	<key>Display Name</key>
	<string>' . $DeviceName . '</string>
	<key>GUID</key>
	<string>' . $GUID . '</string>
	<key>IMEI</key>
	<string>' . $IMEI . '</string>
	<key>Installed Applications</key>
	<array/>
	<key>Last Backup Date</key>
	<date>2018-12-26T01:23:31Z</date>
	<key>Product Type</key>
	<string>' . $ProductType . '</string>
	<key>Product Version</key>
	<string>' . $ProductVersion . '</string>
	<key>Serial Number</key>
	<string>' . $SerialNumber . '</string>
	<key>Target Identifier</key>
	<string>' . $UniqueDeviceID . '</string>
	<key>Target Type</key>
	<string>Device</string>
	<key>Unique Identifier</key>
	<string>' . $UniqueDeviceID . '</string>
	<key>iTunes Files</key>
	<dict>
		<key>IC-Info.sidv</key>
		<data>AAEAAd5/piA8xgXhOz9lrL/5EkzWvd0AYo/CWHQNN6CiO+EPU3w1oaxNPkVpagxFUPkxwGNrxLM4fdi2yDbuaZNvx7GVRCwiuQY3zyhNT2/bKYIr2l1ezQxrBQHPSuY9TlckDiTT3C8/lqxa629TrENmfq4EuANRFS2cMLJJqJzkKJKA2vEfkhSigj/+N0whoWyrYU3u5M79SpmOIX7tcxQuxcy1/9Ek44HWtustnd5AG57gJxlE/kmECmgtdjiXAz8/x99EmBpz2e/2HnRpwtJ/vQWhe7hGsTRZB+0WVCUZWFtJnzRqXGSm9QuZbV5fUwzqorcdy6E26cN3AxyyCfUgh8zpGjtnPYNn4Xy97zru/0xNGVomaFM/tvFHAYupR5wwlQGkJDIHf/SZfV6PVQ7ukBkBfuymLmUxBP5gskuJfVADrUhjnbu6PjbPA/clwhlce7fHNrkU4dmUO9y7dtTFhkgc7PRGg6/B0IJnEdOKLTLgbhY3mDE1Q3ps1459pzG5qo/1XVClremR2Q01+jBiLa1DJy+z95Sn807J0iSkTrcdg8mvjO1hOWZ/5iqX6HIB7iiZpB9uQkqKqg7mfbr/DgOpYsvZz6lOQ9Mf7whhIytp17i7nmvc73wxZ6Awp0Vw7ob12VdFZx4cmIWWmqgGe9CFb23BT4mDwkDSc1SUu6GCQ3Hd+3UzJ1Vq1nf12Hph4UFA++A4k29py53LfHjVv/HMU61FWqbBP6NVReOyJHj7fmbkzsgqCJHWQfCAhtjkq/+YF26Zylsu92nHC/Di0pOo75eYWWpdVsg8z2rxd8h1h3rawLqzTbo/FTHilBfqGStuN8HRLZn63pYwYHukDKur2eJIp/X56h/2ERE6NRNw6mZw8wKqRiMhKVG/92JcdK5iftUY8RcPLHOR4j8zX7u+b79b+sDXqqDkOMi0IEfQceNpjIHth1jW/jyemBouVOlGd/EuBFgCxWGTtJhsBbFw1yOwahSndGVtWR0wBvpeD5uWO/HQn5IrPp/d1XUM7SO0X8uIfn/isTi8pFQ5+mfewrcDwdxvTE+U6E3zws/xzuDN3LS9YI1cMzHIPqg1RB6YutafXAMXURnARZtW1UbVhtKIlRZeT5/8KvRNWUdfI/NlRiVYwGXC6pnvoQ1kGnD1y9Pti/wA889tepDm3Ca2fLgMunpED5ocOFrjOdJF0YI/NEB7NvrASC3AcSYuXuiz/RbnAlTjf4q9z4O+8d8uC2/KtSi6eEL8V9KmA1FlSPOhBzGi7hMjMBeWcfWpxzj/9P6XlnQSXbuhLl95G+925U/lBpsGvIqKu11hjd/+Dsl2e7wppQJQs6IsZjxI3o8TDWHRmXJD78DUFQBAC49dWWVJ87++0IhsYPj/tE9QVjcFpc5+4B9w1+CpYEsr0SgUiu/aXRUhHzoHolXeHv3QAfaCdx+2n/jD+zYYeBVDXuWIpT7JEVmJj70pSEX0Lz2Vhielo5xr/ZxNcuJGqnl89uhAcn/9nRIZfvgspDBy</data>
		<key>PhotosFolderAlbums</key>
		<data>ZnJwZAEAAQAAAAD/AAAAAAQCAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</data>
		<key>PhotosFolderName</key>
		<data>BQCwZfpeh2X2TjlZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</data>
		<key>PhotosFolderPrefs</key>
		<data>ZnJwZAEAAAABAAAACAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQwA6AFwAVQBzAGUAcgBzAFwAaQBNAHkARgBvAG4AZQBcAEQAZQBzAGsAdABvAHAAXABDAGgAZQBuAHMAdwAtAGkATQB5AEYAbwBuAGUAXACwZfpeh2X2TjlZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</data>
		<key>VoiceMemos.plist</key>
		<data>PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdC8+CjwvcGxpc3Q+Cg==</data>
		<key>iTunesPrefs</key>
		<data>ZnJwZAEAGQABAQABvUn1HgYw3taMAG3X8hktgwAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAECAADwnKFU4MO09wAAAAAAAAAAAAAAAQAAAABcm3RT4TiBygABAAQAAAAAvUn1HgYw3tYCAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAEBAAAAAAAAAAAAAAEAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADR0VotFpE6pZN8huO2Hitbq9D9zAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAADwAAAAAAAQABAAAAAAEBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaU15Rm9uZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAElNWUZPTkUtUEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaU15Rm9uZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAElNWUZPTkUtUEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpTXlGb25lAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASU1ZRk9ORS1QQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</data>
		<key>iTunesPrefs.plist</key>
		<data>PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+QXVkaW9ib29rUGxheWxpc3RJRHM8L2tleT4KCTxhcnJheS8+Cgk8a2V5PkF1ZGlvYm9va1RyYWNrSURzPC9rZXk+Cgk8YXJyYXkvPgoJPGtleT5Nb3ZpZVBsYXlsaXN0SURzPC9rZXk+Cgk8YXJyYXkvPgoJPGtleT5Nb3ZpZVRyYWNrSURzPC9rZXk+Cgk8YXJyYXkvPgoJPGtleT5NdXNpY0FsYnVtSURzPC9rZXk+Cgk8YXJyYXkvPgoJPGtleT5NdXNpY0FydGlzdElEczwva2V5PgoJPGFycmF5Lz4KCTxrZXk+TXVzaWNHZW5yZU5hbWVzPC9rZXk+Cgk8YXJyYXkvPgoJPGtleT5NdXNpY1BsYXlsaXN0SURzPC9rZXk+Cgk8YXJyYXkvPgoJPGtleT5NdXNpY1RyYWNrSURzPC9rZXk+Cgk8YXJyYXkvPgoJPGtleT5Qb2RjYXN0Q2hhbm5lbElEczwva2V5PgoJPGFycmF5Lz4KCTxrZXk+UG9kY2FzdFBsYXlsaXN0SURzPC9rZXk+Cgk8YXJyYXkvPgoJPGtleT5Qb2RjYXN0VHJhY2tJRHM8L2tleT4KCTxhcnJheS8+Cgk8a2V5PlRWU2hvd0FsYnVtSURzPC9rZXk+Cgk8YXJyYXkvPgoJPGtleT5UVlNob3dOYW1lczwva2V5PgoJPGFycmF5Lz4KCTxrZXk+VFZTaG93UGxheWxpc3RJRHM8L2tleT4KCTxhcnJheS8+Cgk8a2V5PlRWU2hvd1RyYWNrSURzPC9rZXk+Cgk8YXJyYXkvPgoJPGtleT5pUG9kUHJlZnM8L2tleT4KCTxkYXRhPgoJWm5Kd1pBRUFHUUFCQVFBQnZVbjFIZ1l3M3RhTUFHM1g4aGt0Z3dBQUFBQUFBQUFCQUFBQUFBQUFBQUFBQUFBQUFRQUEKCUFBRUNBQUR3bktGVTRNTzA5d0FBQUFBQUFBQUFBQUFBQVFBQUFBQmNtM1JUNFRpQnlnQUJBQVFBQUFBQXZVbjFIZ1l3CgkzdFlDQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFCQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJQWdBQUFBRUJBQUFBQUFBQUFBQUFBQUVBQVFBQUFBRUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCUFBQUFBRFIwVm90RnBFNnBaTjhodU8ySGl0YnE5RDl6QUFBQUFBQUFBQUFBQUFBQUFBQUFBUDhBQUFBQUFBQUFBQUFBCglBQUFBQUFBQUFBQUFBQUFBQUFBQUFBRUFBQUFBQUFBQUR3QUFBQUFBQVFBQkFBQUFBQUVCZ0FBQUFBQUFBQUFBQUFBQQoJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQWFVMTVSbTl1WlFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCglBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUVsTldVWlBUa1V0VUVNQQoJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCglBQUFBQUFBQUFBQUFBQUFBQUFBQWFVMTVSbTl1WlFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUVsTldVWlBUa1V0VUVNQUFBQUFBQUFBQUFBQUFBQUEKCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUJwVFhsR2IyNWxBQUFBCglBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJQUFBQVNVMVpSazlPUlMxUVF3QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCglBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCglBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCglBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJQUFBQUFBQUFBQUE9Cgk8L2RhdGE+Cgk8a2V5PmlUdW5lc1ZlcnNpb248L2tleT4KCTxzdHJpbmc+MTIuOS4yPC9zdHJpbmc+CjwvZGljdD4KPC9wbGlzdD4K</data>
	</dict>
	<key>iTunes Settings</key>
	<dict/>
	<key>iTunes Version</key>
	<string>12.9.2.6</string>
</dict>
</plist>';

$ManifestPlist = '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>IsEncrypted</key>
	<false/>
	<key>Version</key>
	<string>9.1</string>
	<key>Date</key>
	<date>2018-12-26T01:23:28Z</date>
	<key>SystemDomainsVersion</key>
	<string>16.0</string>
	<key>WasPasscodeSet</key>
	<false/>
	<key>Lockdown</key>
	<dict>
		<key>com.apple.MobileDeviceCrashCopy</key>
		<dict>
			<key>ShouldSubmit</key>
			<false/>
		</dict>
		<key>com.apple.TerminalFlashr</key>
		<dict>
		</dict>
		<key>com.apple.mobile.data_sync</key>
		<dict>
		</dict>
		<key>com.apple.Accessibility</key>
		<dict>
			<key>VoiceOverTouchEnabledByiTunes</key>
			<false/>
		</dict>
		<key>ProductVersion</key>
		<string>' . $ProductVersion . '</string>
		<key>ProductType</key>
		<string>' . $ProductType . '</string>
		<key>BuildVersion</key>
		<string>' . $BuildVersion . '</string>
		<key>com.apple.mobile.iTunes.accessories</key>
		<dict>
		</dict>
		<key>com.apple.mobile.wireless_lockdown</key>
		<dict>
		</dict>
		<key>com.apple.iTunes.backup</key>
		<dict>
			<key>LastBackupComputerName</key>
			<string>PC</string>
			<key>LastBackupComputerType</key>
			<string>PC</string>
		</dict>
		<key>SerialNumber</key>
		<string>' . $SerialNumber . '</string>
		<key>UniqueDeviceID</key>
		<string>' . $UniqueDeviceID . '</string>
		<key>DeviceName</key>
		<string>' . $DeviceName . '</string>
	</dict>
	<key>Applications</key>
	<dict>
		<key>com.apple.WebViewService</key>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.apple.WebViewService</string>
			<key>Path</key>
			<string>/private/var/mobile/Applications/E8594ABE-6081-4E44-8415-EBCDFD024D04/WebViewService.app</string>
			<key>CFBundleVersion</key>
			<string>1.0</string>
		</dict>
		<key>com.apple.weather</key>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.apple.weather</string>
			<key>Path</key>
			<string>/private/var/mobile/Applications/49D2BEF2-69EE-4599-B85E-EA875DFA694A/Weather.app</string>
			<key>CFBundleVersion</key>
			<string>1.0</string>
		</dict>
	</dict>
	<key>BackupKeyBag</key>
	<data>
	VkVSUwAAAAQAAAADVFlQRQAAAAQAAAABVVVJRAAAABBOjdeFZYtKqJeYOLx9Kik9SE1D
	SwAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV1JBUAAA
	AAQAAAAAU0FMVAAAABT2+2RcKXCJOkRUdnhzGpV4GSeVAElURVIAAAAEAAAnEFVVSUQA
	AAAQ2Oqr6vdeS9upNHO8q4jnCkNMQVMAAAAEAAAAAVdSQVAAAAAEAAAAAktUWVAAAAAE
	AAAAAFdQS1kAAAAo6nPmyyCO5IW2oS+6ckGUacrrTrQLgRHBj3pbBkcUQoG2RmXrgTx8
	YlVVSUQAAAAQHYZzvraxRs+LQgNwOFjcnkNMQVMAAAAEAAAAAldSQVAAAAAEAAAAAktU
	WVAAAAAEAAAAAFdQS1kAAAAoLqGMubuKThLU0xMkk0faCjy0sFeOXtwsiphTJ8yasNtc
	2klB/ACc/lVVSUQAAAAQH9OagP7GQTyXVH1V/BsQEkNMQVMAAAAEAAAAA1dSQVAAAAAE
	AAAAAktUWVAAAAAEAAAAAFdQS1kAAAAo1zlncBM+J/+pgw6Y19QMiV1saKRQSEHFjugM
	iWStuDXV8k5CuAm591VVSUQAAAAQFht5sGYCRMCVbHWodqMpe0NMQVMAAAAEAAAABFdS
	QVAAAAAEAAAAAktUWVAAAAAEAAAAAFdQS1kAAAAo0hofFA+sNXMj8t7kGvPJw4CGbz0K
	VgvVQkw1nB5824ys/YARsHFegFVVSUQAAAAQfPJixC/7TnGXJ2GtrTn5i0NMQVMAAAAE
	AAAABVdSQVAAAAAEAAAAA0tUWVAAAAAEAAAAAFdQS1kAAAAovSzDDAlYpz8DfVIhWwKC
	Z0fXQIscKRw9mrkqWzWH60xObG3bFzPpX1VVSUQAAAAQNRR7KhitQRGbWdW4VyF2KUNM
	QVMAAAAEAAAABldSQVAAAAAEAAAAA0tUWVAAAAAEAAAAAFdQS1kAAAAo8EWjjCjzlT1T
	iCzu7EPYseBhKSuLVqc3edr3wl89Tr3ZQa76RFt5HFVVSUQAAAAQ9WS8hf7VRoSJ8zjt
	blOSGkNMQVMAAAAEAAAAB1dSQVAAAAAEAAAAA0tUWVAAAAAEAAAAAFdQS1kAAAAoO41q
	iAz9ZnG+Aiam0PGSKKVJt5umVMMcuJhZG/hUH62s7KIYdqguxlVVSUQAAAAQ0T9KdCb2
	S6+J+rO3EdNYQkNMQVMAAAAEAAAACFdSQVAAAAAEAAAAA0tUWVAAAAAEAAAAAFdQS1kA
	AAAoWUcKzsSOrX3myKGY23Eb38NqlMn5iWiPa1ZokXE+gbtyNdYLw4GUu1VVSUQAAAAQ
	AmxBy1fIRCCPN5uWQMILaUNMQVMAAAAEAAAACVdSQVAAAAAEAAAAA0tUWVAAAAAEAAAA
	AFdQS1kAAAAoLyg5LNcMHC1nBJm4+8hWE2A9bd7WNPmv5hiOydalQ9RP1/QDkIX8ZFVV
	SUQAAAAQav5cXIeZQ5m/CeSjaAvWIkNMQVMAAAAEAAAACldSQVAAAAAEAAAAA0tUWVAA
	AAAEAAAAAFdQS1kAAAAo4PVIdV36ZTr+wj19DJy+C7Eunb8fo3o0P2++ZqHNZO75v+m0
	/Wi1qVVVSUQAAAAQ2aS6EsEOShqesARmVZXt6ENMQVMAAAAEAAAAC1dSQVAAAAAEAAAA
	A0tUWVAAAAAEAAAAAFdQS1kAAAAoMnKdR5ws16PtOykvm34de6MlfTQ8uTGtoqZo4hJ1
	jMIUlSvV3R3Xwg==
	</data>
</dict>
</plist>';
$manifest = file_get_contents('manifest.crt');
file_put_contents($devicefolder.'Info.plist', $InfoPlist);
file_put_contents($devicefolder.'Manifest.plist', $ManifestPlist);
$zip = new ZipArchive();
$zip->open($devicefolder.'/'.$SerialNumber.'.zip', ZipArchive::CREATE);
$zip->addFile($devicefolder.'Info.plist', 'Info.plist');
$zip->addFile($devicefolder.'Manifest.plist', 'Manifest.plist');
$zip->close();
unlink($devicefolder.'Info.plist');
unlink($devicefolder.'Manifest.plist');
echo $manifest;
die();
}
else
{
echo 'What are you looking for?';
die();
}
?>
